### ISSUE TITLE
Weird slices example and explaining references.

### ISSUE THREAD

**Issue by josalhor** [karlseguin/the-little-go-book#52]
In the slices chapter we can see the following block of code:

```
func main() {
	scores := []int{1, 2, 3, 4, 5}
	scores = removeAtIndex(scores, 2)
	fmt.Println(scores)
}
func removeAtIndex(source []int, index int) []int {
	lastIndex := len(source) - 1
	//swap the last value and the value we want to remove
	source[index], source[lastIndex] = source[lastIndex], source[index]
	return source[:lastIndex]
}
```

Because the function is called removeAtIndex I expected the output to be [1 2 4 5]. It first I thought this was a mistake. 

After revising the context, this is not a mistake. It clearly says this:

> The above is the start of an efficient way to remove a value from an unsorted slice:

Now, that being noted, I don't see why this could be changed to the following example: 

https://play.golang.org/p/_iCZmUS-fzT

Arguments in favor:

- It keeps the order of the slice, making the name of the function seem logical regardless of the context of the book.
- It properly shows what happens after calling it with a function. Unlike the example of the book, that overwrites the previous slice.

**Comment by karlseguin** [comment]
I think you're points are valid, but I don't agree that it's a better example. The existing code, with it's flaws (re-ordering), better demonstrates the power of slices: efficient removal of an item (in O(1) time).  Shifting the values in O(N), as you have, might be more idiomatic, but that's precisely what I don't want to show (because it is idiomatic, might as well create a new array and copy all the values over, as you would in any non-slice language).

Not sure if that makes sense?

**Comment by josalhor** [comment]
That makes all the sense in the world.

First of all, I would improve it adding the output as as comment on the print function. That shows that the result is the one intended.

Then, I would suggest: In that case, removeAtIndex could be renamed to removeAtIndexWithoutIndex or simply add a new comment pointing out that the lists is without order. You could also remove the order from the original list. All these three ideas feel sub-optimal, the function name would be too large and more comments feel kind of wrong. 

What do you think about this?

https://play.golang.org/p/WPYF1fLhAi1
